package com.example.asus.apppangan;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DBHelper extends SQLiteOpenHelper {
    private static final String DATABASE_NAME = "appangan.db";
    private static final int DATABASE_VERSION = 1;

    public DBHelper(Context context) {
        super(context, DATABASE_NAME, null, 1);
    }

    public void onCreate(SQLiteDatabase databasena) {

        //TABLE PADINYA
        databasena.execSQL("CREATE TABLE IF NOT EXISTS penyakitpadi (id_penyakit TEXT PRIMARY KEY  NOT NULL  UNIQUE, namapenyakit TEXT NOT NULL, deskripsip TEXT, penyebabp TEXT, pencegahanp TEXT, probabilitas TEXT NOT NULL, gambar BLOB)");
        databasena.execSQL("CREATE TABLE IF NOT EXISTS gejalapadi (id_gejala TEXT PRIMARY KEY NOT NULL UNIQUE, namagejala TEXT NOT NULL)");
        databasena.execSQL("CREATE TABLE IF NOT EXISTS rulepadi (id_rule TEXT PRIMARY KEY  NOT NULL  UNIQUE, id_penyakit TEXT NOT NULL , id_gejala TEXT NOT NULL , probabilitas NUMERIC NOT NULL, FOREIGN KEY(id_penyakit) REFERENCES penyakitpadi(id_penyakit), FOREIGN KEY(id_gejala) REFERENCES gejalapadi(id_gejala))");


        //TABLE KEDELAINYA
        databasena.execSQL("CREATE TABLE IF NOT EXISTS penyakitkedelai (id_penyakit TEXT PRIMARY KEY  NOT NULL  UNIQUE, namapenyakit TEXT NOT NULL, deskripsip TEXT, penyebabp TEXT, pencegahanp TEXT, probabilitas TEXT NOT NULL, gambar BLOB)");
        databasena.execSQL("CREATE TABLE IF NOT EXISTS gejalakedelai (id_gejala TEXT PRIMARY KEY NOT NULL UNIQUE, namagejala TEXT NOT NULL)");
        databasena.execSQL("CREATE TABLE IF NOT EXISTS rulekedelai (id_rule TEXT PRIMARY KEY  NOT NULL  UNIQUE, id_penyakit TEXT NOT NULL , id_gejala TEXT NOT NULL , probabilitas NUMERIC NOT NULL, FOREIGN KEY(id_penyakit) REFERENCES penyakitkedelai(id_penyakit), FOREIGN KEY(id_gejala) REFERENCES gejalakedelai(id_gejala))");

        //TABLE JAGUNGNYA
        databasena.execSQL("CREATE TABLE IF NOT EXISTS penyakitjagung (id_penyakit TEXT PRIMARY KEY  NOT NULL  UNIQUE, namapenyakit TEXT NOT NULL, deskripsip TEXT, penyebabp TEXT, pencegahanp TEXT, probabilitas TEXT NOT NULL, gambar BLOB)");
        databasena.execSQL("CREATE TABLE IF NOT EXISTS gejalajagung (id_gejala TEXT PRIMARY KEY NOT NULL UNIQUE, namagejala TEXT NOT NULL)");
        databasena.execSQL("CREATE TABLE IF NOT EXISTS rulejagung (id_rule TEXT PRIMARY KEY  NOT NULL  UNIQUE, id_penyakit TEXT NOT NULL , id_gejala TEXT NOT NULL , probabilitas NUMERIC NOT NULL, FOREIGN KEY(id_penyakit) REFERENCES penyakitjagung(id_penyakit), FOREIGN KEY(id_gejala) REFERENCES gejalajagung(id_gejala))");



        //PENYAKIT PADINYA SAPPO
        ContentValues contentValues = new ContentValues();
        contentValues.put("id_penyakit", "H001");
        contentValues.put("namapenyakit", "Bercak Daun Cokelat");
        contentValues.put("probabilitas", "0.8");
        databasena.insert("penyakitpadi", null, contentValues);

        contentValues.put("id_penyakit", "H002");
        contentValues.put("namapenyakit", "Blast");
        contentValues.put("probabilitas", "0.6");
        databasena.insert("penyakitpadi", null, contentValues);

        contentValues.put("id_penyakit", "H003");
        contentValues.put("namapenyakit", "Hawar Daun Bakteri");
        contentValues.put("probabilitas", "0.6");
        databasena.insert("penyakitpadi", null, contentValues);

        contentValues.put("id_penyakit", "H004");
        contentValues.put("namapenyakit", "Kerdil Rumput");
        contentValues.put("probabilitas", "0.8");
        databasena.insert("penyakitpadi", null, contentValues);

        contentValues.put("id_penyakit", "H005");
        contentValues.put("namapenyakit", "Bercak Pelepah Daun");
        contentValues.put("probabilitas", "0.8");
        databasena.insert("penyakitpadi", null, contentValues);

        contentValues.put("id_penyakit", "H006");
        contentValues.put("namapenyakit", "Tungro");
        contentValues.put("probabilitas", "0.4");
        databasena.insert("penyakitpadi", null, contentValues);

        contentValues.put("id_penyakit", "H007");
        contentValues.put("namapenyakit", "Busuk Batang");
        contentValues.put("probabilitas", "0.6");
        databasena.insert("penyakitpadi", null, contentValues);





        //PENYAKIT KEDELAINYA SAPPO
        ContentValues penyakitkedelainya = new ContentValues();
        penyakitkedelainya.put("id_penyakit", "H001");
        penyakitkedelainya.put("namapenyakit", "Penyakit Antraknose");
        penyakitkedelainya.put("probabilitas", "0.8");
        databasena.insert("penyakitkedelai", null, penyakitkedelainya);

        penyakitkedelainya.put("id_penyakit", "H002");
        penyakitkedelainya.put("namapenyakit", "Penyakit Karat");
        penyakitkedelainya.put("probabilitas", "0.8");
        databasena.insert("penyakitkedelai", null, penyakitkedelainya);

        penyakitkedelainya.put("id_penyakit", "H003");
        penyakitkedelainya.put("namapenyakit", "Penyakit Pustul Bakteri");
        penyakitkedelainya.put("probabilitas", "0.4");
        databasena.insert("penyakitkedelai", null, penyakitkedelainya);

        penyakitkedelainya.put("id_penyakit", "H004");
        penyakitkedelainya.put("namapenyakit", "Target Spot");
        penyakitkedelainya.put("probabilitas", "0.4");
        databasena.insert("penyakitkedelai", null, penyakitkedelainya);

        penyakitkedelainya.put("id_penyakit", "H005");
        penyakitkedelainya.put("namapenyakit", "Rebah Kecambah, Busuk Daun, Batang & Polong");
        penyakitkedelainya.put("probabilitas", "0.6");
        databasena.insert("penyakitkedelai", null, penyakitkedelainya);



        //PENYAKIT JAGUNGNYA SAPPO
        ContentValues penyakitjagungnya = new ContentValues();
        penyakitjagungnya.put("id_penyakit", "H001");
        penyakitjagungnya.put("namapenyakit", "Bercak Daun");
        penyakitjagungnya.put("probabilitas", "0.8");
        databasena.insert("penyakitjagung", null, penyakitjagungnya);

        penyakitjagungnya.put("id_penyakit", "H002");
        penyakitjagungnya.put("namapenyakit", "Bulai");
        penyakitjagungnya.put("probabilitas", "0.6");
        databasena.insert("penyakitjagung", null, penyakitjagungnya);

        penyakitjagungnya.put("id_penyakit", "H003");
        penyakitjagungnya.put("namapenyakit", "Busuk Batang");
        penyakitjagungnya.put("probabilitas", "0.8");
        databasena.insert("penyakitjagung", null, penyakitjagungnya);

        penyakitjagungnya.put("id_penyakit", "H004");
        penyakitjagungnya.put("namapenyakit", "Hawar Daun");
        penyakitjagungnya.put("probabilitas", "0.8");
        databasena.insert("penyakitjagung", null, penyakitjagungnya);

        penyakitjagungnya.put("id_penyakit", "H005");
        penyakitjagungnya.put("namapenyakit", "Karat Daun");
        penyakitjagungnya.put("probabilitas", "0.4");
        databasena.insert("penyakitjagung", null, penyakitjagungnya);










        //GEJALA PADI NYA SAPPO
        ContentValues contentValues2 = new ContentValues();
        contentValues2.put("id_gejala", "E001");
        contentValues2.put("namagejala", "Menyerang setiap fase pertumbuhan");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E002");
        contentValues2.put("namagejala", "Terjadi bercak belah ketupat pada daun");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E003");
        contentValues2.put("namagejala", "Warna abu \u2013 abu pada bagian tengah");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E004");
        contentValues2.put("namagejala", "Infeksi pada ruas batang dan leher malai");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E005");
        contentValues2.put("namagejala", "Adanya bercak kuning sampai putih dari tepi daun hingga semua daun");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E006");
        contentValues2.put("namagejala", "Terjadi mulai fase persemaian sampe awal fase pembentukan anakan");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E007");
        contentValues2.put("namagejala", "Ujung daun berwarna kuning oranye");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E008");
        contentValues2.put("namagejala", "Berwarna kuning coklat pada daun muda");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E009");
        contentValues2.put("namagejala", "Berwarna coklat kemerahan");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E010");
        contentValues2.put("namagejala", "Menyerang fase pembibitan sampai fase bunting");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E011");
        contentValues2.put("namagejala", "Terjadi bercak coklat berbentuk oval sampai bulat");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E012");
        contentValues2.put("namagejala", "Tanaman Kerdil");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E013");
        contentValues2.put("namagejala", "Jumlah anakkan yang terlalu banyak sehingga seperti rumput");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E014");
        contentValues2.put("namagejala", "Tidak dapat memproduksi malai");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E015");
        contentValues2.put("namagejala", "Daun tanaman padi menjadi sempit, pendek, kaku, berwarna hijau pucat");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E016");
        contentValues2.put("namagejala", "Terjadi bercak kehitaman bentuknya tidak teratur dan membesar");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E017");
        contentValues2.put("namagejala", "Menyerang fase anakan sampai stadia matang susu");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E018");
        contentValues2.put("namagejala", "Timbul bercak \u2013 bercak lebar pada padi");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E019");
        contentValues2.put("namagejala", "Terjadi di fase pembungaan dan pemasakan");
        databasena.insert("gejalapadi", null, contentValues2);
        contentValues2.put("id_gejala", "E020");
        contentValues2.put("namagejala", "Seluruh daun menggulung, layu, dan mati");
        databasena.insert("gejalapadi", null, contentValues2);




        //GEJALA KEDELAI NYA SAPPO
        ContentValues gejalakedelainya = new ContentValues();
        gejalakedelainya.put("id_gejala", "E001");
        gejalakedelainya.put("namagejala", "Tanaman mengering dan mati");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E002");
        gejalakedelainya.put("namagejala", "Lapisan akar dan batang menjadi kecoklatan");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E003");
        gejalakedelainya.put("namagejala", "Adanya bintik hitam berupa duri jamur pada batang");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E004");
        gejalakedelainya.put("namagejala", "Timbulnya Bercak berwarna coklat kemerahan");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E005");
        gejalakedelainya.put("namagejala", "Bercak berwarna coklat pada daun");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E006");
        gejalakedelainya.put("namagejala", "Polong Hampa");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E007");
        gejalakedelainya.put("namagejala", "bintik kecil dibawah permukaan daun kedelai");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E008");
        gejalakedelainya.put("namagejala", "Bercak membentuk lingkaran seperti pada papan tembak");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E009");
        gejalakedelainya.put("namagejala", "Polong Membusuk");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E010");
        gejalakedelainya.put("namagejala", "Akar dan batang menjadi busuk");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E011");
        gejalakedelainya.put("namagejala", "Penebalan tulang daun");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E012");
        gejalakedelainya.put("namagejala", "Kerontokan daun kedelai");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E013");
        gejalakedelainya.put("namagejala", "Tanaman layu mendadak");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E014");
        gejalakedelainya.put("namagejala", "Benih tidak mampu tumbuh");
        databasena.insert("gejalakedelai", null, gejalakedelainya);
        gejalakedelainya.put("id_gejala", "E015");
        gejalakedelainya.put("namagejala", "Daun berwarna kecoklatan");
        databasena.insert("gejalakedelai", null, gejalakedelainya);




        //GEJALA JAGUNGNYA SAPPO
        ContentValues gejalajagungnya = new ContentValues();
        gejalajagungnya.put("id_gejala", "E001");
        gejalajagungnya.put("namagejala", "Bercak berwarna hijau ke abu-abuan atau coklat");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E002");
        gejalajagungnya.put("namagejala", "Pangkal batang berwarna kecoklatan");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E003");
        gejalajagungnya.put("namagejala", "Pertumbuhan kerdil");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E004");
        gejalajagungnya.put("namagejala", "Tongkol jagung gugur");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E005");
        gejalajagungnya.put("namagejala", "Bercak menghasilkan uredospora");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E006");
        gejalajagungnya.put("namagejala", "Permukaan daun jagung berwarna putih kekuingan");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E007");
        gejalajagungnya.put("namagejala", "Bercak kecil berbentuk bulat");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E008");
        gejalajagungnya.put("namagejala", "Biji rusak dan busuk");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E009");
        gejalajagungnya.put("namagejala", "Tanaman cepat mati / Mengering");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E010");
        gejalajagungnya.put("namagejala", "Batang mudah sekali rebah");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E011");
        gejalajagungnya.put("namagejala", "Bercak berwarna hijau kekuningan / Coklat pada daun");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E012");
        gejalajagungnya.put("namagejala", "Kulit luar batang tipis");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E013");
        gejalajagungnya.put("namagejala", "Munculnya garis-garis klorotik pada daun");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E014");
        gejalajagungnya.put("namagejala", "Bercak kerdil berbetnuk oval");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E015");
        gejalajagungnya.put("namagejala", "Tanaman layu kurung waktu 3/4 minggu");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E016");
        gejalajagungnya.put("namagejala", "Bagian dalam batang membusuk");
        databasena.insert("gejalajagung", null, gejalajagungnya);
        gejalajagungnya.put("id_gejala", "E017");
        gejalajagungnya.put("namagejala", "Bercak memanjang berbentuk elips");
        databasena.insert("gejalajagung", null, gejalajagungnya);





       //RULE /ATURAN PADINYA SAPPO
        ContentValues contentValues3 = new ContentValues();
        contentValues3.put("id_rule", "R001");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E001");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R002");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E002");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R003");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E003");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R004");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E004");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R005");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E005");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R006");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E006");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R007");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E007");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R008");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E008");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R009");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E009");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R010");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E010");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R011");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E011");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R012");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E012");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R013");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E013");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R014");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E014");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R015");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E015");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R016");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E016");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R017");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E017");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R018");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E018");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R019");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E019");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R020");
        contentValues3.put("id_penyakit", "H001");
        contentValues3.put("id_gejala", "E020");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R021");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E001");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R022");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E002");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R023");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E003");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R024");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E004");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R025");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E005");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R026");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E006");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R027");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E007");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R028");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E008");
        contentValues3.put("probabilitas", "0.7");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R029");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E009");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R030");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E010");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R031");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E011");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R032");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E012");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R033");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E013");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R034");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E014");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R035");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E015");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R036");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E0016");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R037");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E017");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R038");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E018");
        contentValues3.put("probabilitas", "0.7");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R039");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E019");
        contentValues3.put("probabilitas", "0.7");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R040");
        contentValues3.put("id_penyakit", "H002");
        contentValues3.put("id_gejala", "E020");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R041");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E001");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R042");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E002");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R043");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E003");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R044");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E004");
        contentValues3.put("probabilitas", "0.2");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R045");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E005");
        contentValues3.put("probabilitas", "0.7");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R046");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E006");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R047");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E007");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R048");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E008");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R049");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E009");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R050");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E010");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R051");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E011");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R052");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E012");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R053");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E013");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R054");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E014");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R055");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E015");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R056");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E016");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R057");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E017");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R058");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E018");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R059");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E019");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R060");
        contentValues3.put("id_penyakit", "H003");
        contentValues3.put("id_gejala", "E020");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R061");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E001");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R062");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E002");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R063");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E003");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R064");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E004");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R065");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E005");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R066");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E006");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R067");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E007");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R068");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E008");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R069");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E009");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R070");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E010");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R071");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E011");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R072");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E012");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R073");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E013");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R074");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E014");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R075");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E015");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R076");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E016");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R077");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E017");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R078");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E018");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R079");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E019");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R080");
        contentValues3.put("id_penyakit", "H004");
        contentValues3.put("id_gejala", "E020");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R081");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E001");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R082");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E002");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R083");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E003");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R084");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E004");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R085");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E005");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R086");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E006");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R087");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E007");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R088");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E008");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R089");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E009");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R090");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E010");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R091");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E011");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R092");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E012");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R093");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E013");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R094");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E014");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R095");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E015");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R096");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E016");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R097");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E017");
        contentValues3.put("probabilitas", "0.7");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R098");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E018");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R099");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E019");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R100");
        contentValues3.put("id_penyakit", "H005");
        contentValues3.put("id_gejala", "E020");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R101");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E001");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R102");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E002");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R103");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E003");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R104");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E004");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R105");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E005");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R106");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E006");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R107");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E007");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R108");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E008");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R109");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E009");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R110");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E010");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R111");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E011");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R112");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E012");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R113");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E013");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R114");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E014");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R115");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E015");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R116");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E016");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R117");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E017");
        contentValues3.put("probabilitas", "0.7");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R118");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E018");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R119");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E019");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R120");
        contentValues3.put("id_penyakit", "H006");
        contentValues3.put("id_gejala", "E020");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R121");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E001");
        contentValues3.put("probabilitas", "0.8");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R122");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E002");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R123");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E003");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R124");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E004");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R125");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E005");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R126");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E006");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R127");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E007");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R128");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E008");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R129");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E009");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R130");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E010");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R131");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E011");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R132");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E012");
        contentValues3.put("probabilitas", "0.4");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R133");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E013");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R134");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E014");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R135");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E015");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R136");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E016");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R137");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E017");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R138");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E018");
        contentValues3.put("probabilitas", "0");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R139");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E019");
        contentValues3.put("probabilitas", "0.9");
        databasena.insert("rulepadi", null, contentValues3);
        contentValues3.put("id_rule", "R140");
        contentValues3.put("id_penyakit", "H007");
        contentValues3.put("id_gejala", "E020");
        contentValues3.put("probabilitas", "0.6");
        databasena.insert("rulepadi", null, contentValues3);





        //RULE /ATURAN KEDELAINYA SAPPO
        ContentValues aturanrulekedelai = new ContentValues();
        aturanrulekedelai.put("id_rule", "R001");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E001");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R002");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E002");
        aturanrulekedelai.put("probabilitas", "0.9");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R003");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E003");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R004");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E004");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R005");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E005");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R006");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E006");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R007");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E007");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R008");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E008");
        aturanrulekedelai.put("probabilitas", "0.9");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R009");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E009");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R010");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E010");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R011");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E011");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R012");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E012");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R013");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E013");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R014");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E014");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R015");
        aturanrulekedelai.put("id_penyakit", "H001");
        aturanrulekedelai.put("id_gejala", "E015");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R016");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E001");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R017");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E002");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R018");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E003");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R019");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E004");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R020");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E005");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R021");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E006");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R022");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E007");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R023");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E008");
        aturanrulekedelai.put("probabilitas", "0.7");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R024");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E009");
        aturanrulekedelai.put("probabilitas", "0.6");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R025");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E010");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R026");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E011");
        aturanrulekedelai.put("probabilitas", "0.6");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R027");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E012");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R028");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E013");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R029");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E014");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R030");
        aturanrulekedelai.put("id_penyakit", "H002");
        aturanrulekedelai.put("id_gejala", "E015");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R031");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E001");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R032");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E002");
        aturanrulekedelai.put("probabilitas", "0.9");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R033");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E003");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R034");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E004");
        aturanrulekedelai.put("probabilitas", "0.2");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R035");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E005");
        aturanrulekedelai.put("probabilitas", "0.7");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R036");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E006");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R037");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E007");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R038");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E008");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R039");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E009");
        aturanrulekedelai.put("probabilitas", "0.6");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R040");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E010");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R041");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E011");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R042");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E012");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R043");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E013");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R044");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E014");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R045");
        aturanrulekedelai.put("id_penyakit", "H003");
        aturanrulekedelai.put("id_gejala", "E015");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R046");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E001");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R047");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E002");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R048");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E003");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R049");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E004");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R050");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E005");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R051");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E006");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R052");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E007");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R053");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E008");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R054");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E009");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R055");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E010");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R056");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E011");
        aturanrulekedelai.put("probabilitas", "0");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R057");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E012");
        aturanrulekedelai.put("probabilitas", "0.9");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R058");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E013");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R059");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E014");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R060");
        aturanrulekedelai.put("id_penyakit", "H004");
        aturanrulekedelai.put("id_gejala", "E015");
        aturanrulekedelai.put("probabilitas", "0.9");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R061");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E001");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R062");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E002");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R063");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E003");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R064");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E004");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R065");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E005");
        aturanrulekedelai.put("probabilitas", "0.9");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R066");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E006");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R067");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E007");
        aturanrulekedelai.put("probabilitas", "0.9");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R068");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E008");
        aturanrulekedelai.put("probabilitas", "0.6");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R069");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E009");
        aturanrulekedelai.put("probabilitas", "0.6");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R070");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E010");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R071");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E011");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R072");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E012");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R073");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E013");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R074");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E014");
        aturanrulekedelai.put("probabilitas", "0.4");
        databasena.insert("rulekedelai", null, aturanrulekedelai);
        aturanrulekedelai.put("id_rule", "R075");
        aturanrulekedelai.put("id_penyakit", "H005");
        aturanrulekedelai.put("id_gejala", "E015");
        aturanrulekedelai.put("probabilitas", "0.8");
        databasena.insert("rulekedelai", null, aturanrulekedelai);



        //RULE /ATURAN JAGUNGNYA SAPPO
        ContentValues aturanrulejagung = new ContentValues();
        aturanrulejagung.put("id_rule", "R001");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E001");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R002");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E002");
        aturanrulejagung.put("probabilitas", "0.9");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R003");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E003");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R004");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E004");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R005");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E005");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R006");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E006");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R007");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E007");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R008");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E008");
        aturanrulejagung.put("probabilitas", "0.9");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R009");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E009");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R010");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E010");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R011");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E011");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R012");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E012");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R013");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E013");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R014");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E014");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R015");
        aturanrulejagung.put("id_penyakit", "H001");
        aturanrulejagung.put("id_gejala", "E015");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R016");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E001");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R017");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E002");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R018");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E003");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R019");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E004");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R020");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E005");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R021");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E006");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R022");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E007");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R023");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E008");
        aturanrulejagung.put("probabilitas", "0.7");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R024");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E009");
        aturanrulejagung.put("probabilitas", "0.6");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R025");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E010");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R026");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E011");
        aturanrulejagung.put("probabilitas", "0.6");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R027");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E012");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R028");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E013");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R029");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E014");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R030");
        aturanrulejagung.put("id_penyakit", "H002");
        aturanrulejagung.put("id_gejala", "E015");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R031");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E001");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R032");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E002");
        aturanrulejagung.put("probabilitas", "0.9");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R033");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E003");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R034");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E004");
        aturanrulejagung.put("probabilitas", "0.2");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R035");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E005");
        aturanrulejagung.put("probabilitas", "0.7");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R036");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E006");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R037");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E007");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R038");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E008");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R039");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E009");
        aturanrulejagung.put("probabilitas", "0.6");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R040");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E010");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R041");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E011");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R042");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E012");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R043");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E013");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R044");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E014");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R045");
        aturanrulejagung.put("id_penyakit", "H003");
        aturanrulejagung.put("id_gejala", "E015");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R046");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E001");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R047");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E002");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R048");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E003");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R049");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E004");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R050");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E005");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R051");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E006");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R052");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E007");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R053");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E008");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R054");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E009");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R055");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E010");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R056");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E011");
        aturanrulejagung.put("probabilitas", "0");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R057");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E012");
        aturanrulejagung.put("probabilitas", "0.9");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R058");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E013");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R059");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E014");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R060");
        aturanrulejagung.put("id_penyakit", "H004");
        aturanrulejagung.put("id_gejala", "E015");
        aturanrulejagung.put("probabilitas", "0.9");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R061");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E001");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R062");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E002");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R063");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E003");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R064");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E004");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R065");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E005");
        aturanrulejagung.put("probabilitas", "0.9");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R066");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E006");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R067");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E007");
        aturanrulejagung.put("probabilitas", "0.9");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R068");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E008");
        aturanrulejagung.put("probabilitas", "0.6");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R069");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E009");
        aturanrulejagung.put("probabilitas", "0.6");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R070");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E010");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R071");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E011");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R072");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E012");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R073");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E013");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R074");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E014");
        aturanrulejagung.put("probabilitas", "0.4");
        databasena.insert("rulejagung", null, aturanrulejagung);
        aturanrulejagung.put("id_rule", "R075");
        aturanrulejagung.put("id_penyakit", "H005");
        aturanrulejagung.put("id_gejala", "E015");
        aturanrulejagung.put("probabilitas", "0.8");
        databasena.insert("rulejagung", null, aturanrulejagung);





    }

    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS penyakitpadi");
        onCreate(db);
        db.execSQL("DROP TABLE IF EXISTS gejalapadi");
        onCreate(db);
        db.execSQL("DROP TABLE IF EXISTS rulepadi");
        onCreate(db);
    }
}
